# Default values for pangolin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

settings:
  pangolin:
    serverSecretKey: ''
    email:
      enabled: false

  traefik:
    badgerVersion: "v1.2.0"
    certificatesResolver:
      email: ""

deployments:
  pangolin:
    replicaCount: 1
    image:
      repository: "fosrl/pangolin"
      pullPolicy: IfNotPresent
      tag: "1.12.1"
  gerbil:
    replicaCount: 1
    image:
      repository: "fosrl/gerbil"
      pullPolicy: IfNotPresent
      tag: "1.2.2"
  traefik:
    replicaCount: 1
    image:
      repository: "traefik"
      pullPolicy: IfNotPresent
      tag: "3.4.0"

ingress:
  hostDomain: pangolin.test

# Additional volumes on the output Deployment definition.
volumes: []
